// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array                  = require("bs-platform/lib/js/array.js");
var Block                    = require("bs-platform/lib/js/block.js");
var Curry                    = require("bs-platform/lib/js/curry.js");
var ReasonReact              = require("reason-react/lib/js/src/ReasonReact.js");
var TimelineItem             = require("./TimelineItem.js");
var TimelineItemData         = require("./TimelineItemData.js");
var Text$BsReactNative       = require("bs-react-native/lib/js/src/components/text.js");
var ScrollView$BsReactNative = require("bs-react-native/lib/js/src/components/scrollView.js");

var component = ReasonReact.reducerComponent("Timeline");

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      var handleLoaded = Curry._1(self[/* reduce */1], (function (timelineItemsData) {
              return /* Loaded */[timelineItemsData];
            }));
      TimelineItemData.fetchTimelineItems(/* () */0).then((function (timelineItemsData) {
              Curry._1(handleLoaded, timelineItemsData);
              return Promise.resolve(/* () */0);
            }));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (self) {
      var match = self[/* state */2][/* timelineItemsData */0];
      var timelineItems = match ? $$Array.map((function (timelineItem) {
                return ReasonReact.element(/* Some */[timelineItem[/* id */0]], /* None */0, TimelineItem.make(timelineItem, /* array */[]));
              }), match[0]) : ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["loading"], /* array */[]));
      return ReasonReact.element(/* None */0, /* None */0, ScrollView$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[timelineItems]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* timelineItemsData : None */0];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* timelineItemsData : Some */[action[0]]]]);
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
