// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                          = require("bs-platform/lib/js/block.js");
var Curry                          = require("bs-platform/lib/js/curry.js");
var ReasonReact                    = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative                    = require("react-native");
var Text$BsReactNative             = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative             = require("bs-react-native/lib/js/src/components/view.js");
var Image$BsReactNative            = require("bs-react-native/lib/js/src/components/image.js");
var Style$BsReactNative            = require("bs-react-native/lib/js/src/style.js");
var StyleSheet$BsReactNative       = require("bs-react-native/lib/js/src/styleSheet.js");
var TouchableOpacity$BsReactNative = require("bs-react-native/lib/js/src/components/touchableOpacity.js");

var styles = StyleSheet$BsReactNative.create({
      timelineItem: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.paddingBottom(/* Pt */Block.__(0, [20])),
              /* :: */[
                Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [20])),
                /* :: */[
                  Style$BsReactNative.borderBottomWidth(1),
                  /* [] */0
                ]
              ]
            ]
          ]),
      user: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.alignItems(/* Center */2),
            /* :: */[
              Style$BsReactNative.flexDirection(/* Row */0),
              /* :: */[
                Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [10])),
                /* [] */0
              ]
            ]
          ]),
      userImage: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.height(/* Pt */Block.__(0, [50])),
            /* :: */[
              Style$BsReactNative.marginRight(/* Pt */Block.__(0, [20])),
              /* :: */[
                Style$BsReactNative.width(/* Pt */Block.__(0, [50])),
                /* [] */0
              ]
            ]
          ]),
      userName: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [20])),
            /* [] */0
          ]),
      repoName: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [16])),
            /* [] */0
          ])
    });

var component = ReasonReact.statelessComponent("TimelineItem");

function openLink(url) {
  ReactNative.Linking.openURL(url);
  return /* () */0;
}

function make(timelineItem, _) {
  var match = timelineItem[/* body */5];
  var body = match ? match[0] : "";
  var match$1 = timelineItem[/* eventLink */6];
  var eventLink = match$1 ? match$1[0] : "";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.timelineItem], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                      ReasonReact.element(/* None */0, /* None */0, TouchableOpacity$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.user], /* None */0, /* Some */[(function () {
                                      ReactNative.Linking.openURL("https://github.com/" + timelineItem[/* username */2]);
                                      return /* () */0;
                                    })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                                ReasonReact.element(/* None */0, /* None */0, Image$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* URI */Block.__(0, [Curry.app(Image$BsReactNative.imageURISource, [
                                                      timelineItem[/* userImage */3],
                                                      /* None */0,
                                                      /* None */0,
                                                      /* None */0,
                                                      /* None */0,
                                                      /* None */0,
                                                      /* None */0,
                                                      /* None */0,
                                                      /* None */0,
                                                      /* () */0
                                                    ])])], /* Some */[styles.userImage], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                                ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.userName], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[timelineItem[/* username */2]], /* array */[]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, TouchableOpacity$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                      ReactNative.Linking.openURL("https://github.com/" + timelineItem[/* repo */4]);
                                      return /* () */0;
                                    })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.repoName], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["repo: " + timelineItem[/* repo */4]], /* array */[]))])),
                      ReasonReact.element(/* None */0, /* None */0, TouchableOpacity$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                      ReactNative.Linking.openURL(eventLink);
                                      return /* () */0;
                                    })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[body], /* array */[]))]))
                    ]));
    });
  return newrecord;
}

exports.styles    = styles;
exports.component = component;
exports.openLink  = openLink;
exports.make      = make;
/* styles Not a pure module */
