// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                   = require("bs-platform/lib/js/curry.js");
var Js_json                 = require("bs-platform/lib/js/js_json.js");
var Json_decode             = require("bs-json/lib/js/src/Json_decode.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function unwrapUnsafely(data) {
  if (data) {
    return data[0];
  } else {
    throw [
          Caml_builtin_exceptions.invalid_argument,
          "unwrapUnsafely called on None"
        ];
  }
}

var Option = /* module */[/* unwrapUnsafely */unwrapUnsafely];

function buildTimelineItem(timelineItemJson) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, timelineItemJson),
          /* eventType */Json_decode.field("type", Json_decode.string, timelineItemJson),
          /* username */Curry._1(Json_decode.at(/* :: */[
                    "actor",
                    /* :: */[
                      "display_login",
                      /* [] */0
                    ]
                  ], Json_decode.string), timelineItemJson),
          /* userImage */Curry._1(Json_decode.at(/* :: */[
                    "actor",
                    /* :: */[
                      "avatar_url",
                      /* [] */0
                    ]
                  ], Json_decode.string), timelineItemJson),
          /* repo */Curry._1(Json_decode.at(/* :: */[
                    "repo",
                    /* :: */[
                      "name",
                      /* [] */0
                    ]
                  ], Json_decode.string), timelineItemJson),
          /* body */Json_decode.optional(Json_decode.at(/* :: */[
                    "payload",
                    /* :: */[
                      "comment",
                      /* :: */[
                        "body",
                        /* [] */0
                      ]
                    ]
                  ], Json_decode.string), timelineItemJson),
          /* eventLink */Json_decode.optional(Json_decode.at(/* :: */[
                    "payload",
                    /* :: */[
                      "comment",
                      /* :: */[
                        "html_url",
                        /* [] */0
                      ]
                    ]
                  ], Json_decode.string), timelineItemJson)
        ];
}

function fetchTimelineItems() {
  return fetch("https://api.github.com/users/craigsheen/received_events").then((function (prim) {
                      return prim.json();
                    })).then((function (json) {
                    return Promise.resolve(Js_json.decodeArray(json));
                  })).then((function (opt) {
                  return Promise.resolve(unwrapUnsafely(opt));
                })).then((function (timelineItems) {
                return Promise.resolve(timelineItems.map(buildTimelineItem));
              }));
}

exports.Option             = Option;
exports.buildTimelineItem  = buildTimelineItem;
exports.fetchTimelineItems = fetchTimelineItems;
/* No side effect */
