// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function getItems() {
  return /* :: */[
          /* record */[
            /* id */1,
            /* username */"Craig",
            /* title */"Did something"
          ],
          /* :: */[
            /* record */[
              /* id */2,
              /* username */"Hannah",
              /* title */"Something else"
            ],
            /* [] */0
          ]
        ];
}

exports.getItems = getItems;
/* No side effect */
